{% set name = "ccs_fit" %}
{% set version = "0.11.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ccs_fit-{{ version }}.tar.gz
  sha256: da911fbbc6d561577a4e9c561b99b9432a9dc97d535aeefd7bf498d72af1b749

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - poetry
  run:
    - python >=3.9
    - ase >=3.22.1
    - cvxopt >=1.3.0
    - numpy >=1.22.4,<1.23.0
    - pandas >=1.5.0
    - scipy >=1.9.2
    - sympy >=1.11.1
    - tqdm >=4.64.1

test:
  imports:
    - ccs_fit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Teoroo-CMC/CCS
  summary: Fitting tools for repulsive two body interactions using curvature constrained splines.
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ThijsSmolders
