name: CI-CD

# Controls when the workflow will run
on: [push, pull_request]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install package
        run: poetry install

      - name: Test with pytest
        run: poetry run pytest tests/ --cov=ccs --cov-report=xml

      # Optional, but useful
      # - name: Use Codecov to track test coverage
      #   uses: codecov/codecov-action@v2
      #   with:
      #     files: ./coverage.xml

      - name: Build documentation
        run: poetry run make html --directory docs/